#!/bin/bash

BOARD=$(cat /boot/boot/batocera.board)
# We only want the script to run for these devices
if [ "$BOARD" != "trimui-brick" ] && [ "$BOARD" = "trimui-smart-pro" ]; then
    exit 1
fi

case "${1}" in
   suspend)
      ifconfig wlan0 down
      ;;
   resume)
      ifconfig wlan0 up
      ;;
esac
exit 0

