#!/bin/bash

disabled_packages="BUSYBOX_SHOW_OTHERS SKELETON.* BATOCERA_TARGET_H700 \
 HOST_.* MALI_G31_FBDEV \
 BTRFS_PROGS WINBTRFS LIBRETRO.* BATOCERA_.*_SYSTEMS \
 .*MUPEN64.* RETROARCH.* CGENIUS DEVILUTIONX SDLPOP CANNONBALL XASH3D_FWGS \
 HLSDK_XASH3D HLSDK_XASH3D_DMC HLSDK_XASH3D_OPFOR ECWOLF SONIC2013 SONICCD \
 CDOGS ABUSE HCL GZDOOM EDUKE32 RAZE IOQUAKE3 CORSIXTH TYRIAN HURRICAN \
 OPENJAZZ FALLOUT1_CE FALLOUT2_CE IORTCW TARADINO OD_COMMANDER.* \
 HYPSEUS.* JSTEST2 FDUPES BATOCERA_PYGAME XXD PACMAN EVMAPY EVSIEVE \
 EVMAPY_SYSTEM_CONFIG PM_UTILS MANGOHUD SYNCTHING BATOCERA_ETHTOOL \
 HOTKEYGEN BTOP OD_COMMANDER BATOCERA_TEST LEDSPICER INNOEXTRACT WSDD \
 ZRAMSWAP CLEVIS FAKE_HWCLOCK BATOCERA_EMULATIONSTATION.* BATOCERA_ES_.* \
 ES_.* QTSIXA.* UMTOOL WPA_SUPPLICANT_K44.* RTL8812AU \
 BATOCERA_BEZEL KNULLI_BEZELS BATOCERA_RETROACHIEVEMENTS_SOUNDS \
 BATOCERA_SHADERS GLSL_SHADERS AMIBERRY HATARI DOSBOX_STAGING DOSBOX_X \
 MOONLIGHT_EMBEDDED LIGHTSPARK DRASTIC LEXALOFFLE_PICO8 SIMCOUPE PPSSPP \
 FLYCAST SCUMMVM VICE HYPSEUS_SINGE OPENBOR4432 OPENBOR6412 OPENBOR7142 \
 PYTHON_PYGAME2 LIBLCF EASYRPG_PLAYER SOLARUS_ENGINE GSPLUS THEXTECH \
 OPENBOR7530 X16EMU \
 BATOCERA_MUSIC_SUPPORT BATOCERA_SYSTEM BATOCERA_EXTRAS BATOCERA_TOOLS \
 BATOCERA_SEGADC BATOCERA_RETROARCH BATOCERA_WPA BATOCERA_LINUX_FIRMWARES \
 BATOCERA_VIDEO_CODECS BATOCERA_SPLASH_MPV BATOCERA_SETTINGS BATOCERA_IMAGE \
 BATOCERA_UDEV_RULES BATOCERA_USERDATAINIT BATOCERA_BLUETOOTH \
 BATOCERA_NOTICE BATOCERA_CONTROLLER_OVERLAYS BATOCERA_RESOLUTION\
 CIFS_UTILS DOSFSTOOLS DOSFSTOOLS_FSCK_FAT DOSFSTOOLS_MKFS_FAT E2FSPROGS \
 E2FS.* EXFAT.* NFS.* NTFS.* SQUASHFS.* GPTF.* I2C_TOOLS LUA.* \
 ELFUTILS AVAHI.* BLUEZ5.* CONNMAN.* DROPBEAR.* ETHTOOL.* \
 BZIP2 GZIP P7ZIP P7ZIP_7ZR UNRAR UNZIP XZ ZIP ZSTD \
 LSOF DIFFUTILS DOS2UNIX FINDUTILS GAWK GREP JQ LIBTOOL SED TREE \
 FBDUMP FBGRAB LIRC_TOOLS PARTED PCIUTILS PIGPIO SMARTMONTOOLS \
 USB.* FPING GESFTPSERVER IFUPDOWN.* IPROUTE2 IPTABLES IPUTILS.* \
 IW MOSQUITTO NET_TOOLS NETCAT NTP NTP_NTPD OPENRESOLV OPENVPN.* \
 RPCBIND RSYNC SAMBA4 WGET WIREGUARD_TOOLS WIRELESS_.* WPA_.* \
 INOTIFY_TOOLS WHICH ANDROID_TOOLS.* COREUTILS DEBIANUTILS \
 HTOP INITSCRIPTS IRQBALANCE KEYUTILS KMOD.* NCDU  PROCPS_NG PSMISC \
 START_STOP_DAEMON SYSKLOGD.* SYSVINIT TAR TPM2_TOOLS UTIL_LINUX.* \
 WATCHDOG LESS MC NANO.* VIM.* WATCHDOGD.* \
 QEMU_CUSTOM_TARGETS REFPOLICY_POLICY_VERSION BR2_PACKAGE_OPENBLAS_.* \
 LLVM_TARGET_ARCH BR2_PACKAGE_LIBGPG_ERROR_SYSCFG BR2_PACKAGE_LIBSPDM_CPU_FAMILY \
 .*TARGET_ARCH.* LINUXCONSOLETOOLS.* .*FIRMWARE.* BATOCERA_CONFIGGEN \
 BR2_PACKAGE_BATOCERA_INITRAMFS .*TRIGGERHAPPY.* \
 GST1_PLUGINS_BAD_PLUGIN_BLUEZ # build fails if this is enabled \
"

make h700-config

sed '/Target pack/,$!d' ./output/h700/.config | grep -v ^\# > armhf_packages

grep ^BR2_PACKAGE armhf_packages \
 | grep -v BR2_PACKAGE_HAS | grep -v BR2_PACKAGE_PROVIDES \
 | grep -v aarch64 | grep -v Aarch64 | grep -v a64 | grep -v ARMV8 \
 > armhf_packages.grep
mv armhf_packages.grep armhf_packages

for package in $disabled_packages; do
  grep -v "BR2_PACKAGE_${package}=" armhf_packages > armhf_packages.grep
  mv armhf_packages.grep armhf_packages
done

cat armhf_packages >> configs/batocera-h700_armhf_libs.packages
rm armhf_packages

echo Ready to make -j8 h700_armhf_libs-build

